<?php
 $title = 'Appointments List';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('appointment', array('action'=>'add'));?>">Add new Appointment</a>
 </p>

 <table class="table">
 <tr>
     <th>Username</th>
     <th>Reason of visit</th>
     <th>Start time</th>
     <th>End time</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($appointments as $appointment) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($appointment->username);?></td>
     <td><?php echo $this->escapeHtml($appointment->reason_of_visit);?></td>
     <td><?php echo $this->escapeHtml($appointment->start_time);?></td>
     <td><?php echo $this->escapeHtml($appointment->end_time);?></td>
     <td>
         <a href="<?php echo $this->url('appointment',
             array('action'=>'edit', 'id' => $appointment->id));?>">Edit</a>
         <a href="<?php echo $this->url('appointment',
             array('action'=>'delete', 'id' => $appointment->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>